import UIKit

enum FontToken {
    static let a4600: UIFont = .systemFont(ofSize: 16, weight: .semibold)
    static let h0700: UIFont = .systemFont(ofSize: 32, weight: .bold)
    static let h1700: UIFont = .systemFont(ofSize: 28, weight: .bold)
    static let h2500: UIFont = .systemFont(ofSize: 24, weight: .medium)
    static let h3400: UIFont = .systemFont(ofSize: 22, weight: .regular)
    static let t1600: UIFont = .systemFont(ofSize: 17, weight: .semibold)
    static let t2500: UIFont = .systemFont(ofSize: 17, weight: .medium)
    static let t3600: UIFont = .systemFont(ofSize: 16, weight: .semibold)
    static let t8700: UIFont = .systemFont(ofSize: 28, weight: .semibold)
    static let s1500: UIFont = .systemFont(ofSize: 16, weight: .medium)
    static let s2600: UIFont = .systemFont(ofSize: 16, weight: .semibold)
    static let b1600: UIFont = .systemFont(ofSize: 17, weight: .semibold)
    static let b2600: UIFont = .systemFont(ofSize: 13, weight: .semibold)
    static let b4400: UIFont = .systemFont(ofSize: 16, weight: .regular)
    static let b5400: UIFont = .systemFont(ofSize: 15, weight: .regular)
    static let l1500: UIFont = .systemFont(ofSize: 17, weight: .medium)
    static let l2600: UIFont = .systemFont(ofSize: 16, weight: .semibold)
    static let l3500: UIFont = .systemFont(ofSize: 16, weight: .medium)
    static let l4500: UIFont = .systemFont(ofSize: 13, weight: .medium)
    static let l5500: UIFont = .systemFont(ofSize: 10, weight: .medium)
    static let b1400: UIFont = .systemFont(ofSize: 17, weight: .regular)
    static let b2400: UIFont = .systemFont(ofSize: 15, weight: .regular)
    static let b3400: UIFont = .systemFont(ofSize: 13, weight: .regular)
    static let c1600: UIFont = .systemFont(ofSize: 12, weight: .semibold)
    static let c2400: UIFont = .systemFont(ofSize: 12, weight: .regular)
    static let c3400: UIFont = .systemFont(ofSize: 11, weight: .regular)
}
